name: passie
title: Passie
adopt-info: passie
base: core22 
version: '1.0'
license: GPL-3.0
source-code: https://github.com/peter-kal/passie.git
issues: https://github.com/peter-kal/passie/issues

summary: A simple yet, powerful password generator.
description: |
  Passie is a password generator build with Flutter, and Yaru widgets.

grade: stable
confinement: strict 
compression: lzo
architectures: [amd64]

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: stable
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
      - xz-utils
      - zip
    prime:
      - -*







  passie:
    plugin: nil
    source: https://github.com/peter-kal/passie.git
    after: [flutter-git]
    
    override-build: |
      set -eux
      flutter doctor
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/


slots:
  passie-dbus:
   interface: dbus
   bus: session 
   name: io.peter-kal.Passie
      
apps:
 passie:
  command: bin/Passie
  extensions: [gnome]
  plugs:
    - x11
    - wayland 
    - desktop
    - desktop-legacy
    - unity7 
  slots:
    - passie-dbus


