name: passie
base: core22
version: '0.1' 
summary: A simple password generator.
description: |
  A simple passoword generator for linux built with Flutter, and yaru widgets.

grade: stable
confinement: devmode 

parts:
  passie:
    plugin: flutter
    source: https://github.com/peter-kal/passie.git
    flutter-target: lib/main.dart


apps: 
 passie: 
  command: passie 
  extensions: [gnome]
  plugs: 
    - x11
    - wayland 
    - desktop 
    - unity7 
    - desktop-legacy
 


