name: passie
title: Passie
base: core22 
version: "2.0"
license: MPL-2.0
source-code: https://github.com/peter-kal/passie
website: https://github.com/peter-kal/passie
issues: https://github.com/peter-kal/passie/issues
icon: snap/gui/passieicon2.png

summary: A simple, yet powerful password generator.
description: |
  Passie is a password generator build with Flutter, and Yaru widgets.
  You are able to choose if you want numbers, symbols, Capital or Lower case letters; as well as the number of characters.
  Passie is Open-Source(licensed under MPL-2.0), and strictly confined, meaning it can't access things it doesn't need to function,
  like: internet, or system files.
  Feel safe generating your passwords.
  

grade: stable
confinement: strict 
compression: lzo
architectures: 
 - amd64 
 - arm64

parts:
 flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.13.2
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $SNAPCRAFT_PART_INSTALL/usr/bin/dart
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''


 passie:
     plugin: nil
    source: https://github.com/peter-kal/passie.git
    after: [flutter-git]
    source-type: git 
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin/lib
      # work around pub get stack overflow # https://github.com/dart-lang/sdk/issues/51068#issuecomment-1396588253
      set +e
      dart pub get
      set -eux
      flutter build linux --release -v
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/


slots:
  passie-dbus:
   interface: dbus
   bus: session 
   name: io.peter-kal.Passie
      
apps:
 passie:
  command: bin/Passie
  desktop: snap/gui/passie.desktop
  extensions: [gnome]
  plugs:
    - x11
    - wayland 
    - desktop
    - desktop-legacy
    - unity7 
    - opengl


